from time import sleep
from selenium.webdriver import Chrome, ChromeOptions
from selenium.webdriver.common.by import By
options = ChromeOptions()
options.add_experimental_option("detach",True)
driver = Chrome(options=options)
# driver.get("https://amazon.com")
# sleep(2)
# driver.find_element(By.ID,'userName').send_keys("Sahaj Sharma")
# username=driver.find_element(By.ID,"userName")
# username.send_keys("Sahaj Sharma")
# user_email=driver.find_element(By.ID,"userEmail")
# user_email.send_keys("ajsahajsharma@gmail.com")
# user_address=driver.find_element(By.ID,"currentAddress")
# user_address.send_keys("Raghav Dreams Homes")
# user_per_address=driver.find_element(By.ID,"permanentAddress")
# user_per_address.send_keys("Panache Valley")
# sleep(2)
# driver.find_element(By.ID,"submit").click()
# sleep(10)
# # driver.quit()
#
# data=driver.find_element(By.ID,"twotabsearchtextbox")
# data.send_keys("Moai statues")
# sleep(1)
# driver.find_element(By.ID,"nav-search-submit-button").click()
# sleep(2)
#
# data2=driver.find_element(By.CLASS_NAME,"nav-input.nav-progressive-attribute")
# .clean()
# data2.send_keys("iphone 17 pro max ")
# driver.find_element(By.CLASS_NAME,"nav-input.nav-progressive-attribute").click()
driver.get('https://demoqa.com/text-box')

search = driver.find_element(By.TAG_NAME, 'input')
searchButton = driver.find_element(By.TAG_NAME, 'textarea')
search.send_keys('Sahaj')
searchButton.send_keys('maybe im over here or over there')
sleep(10)
driver.quit()